# Import the relevant libraries

In [1]:
import numpy as np

## Addition

### Addition of scalars

In [2]:
5 + 5

10

In [3]:
10 - 4

6

### Addition of matrices

In [13]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [14]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [15]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### Addition of vectors

In [16]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [17]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [18]:
v1+v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Exceptions (addition with a scalar)

In [19]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [20]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [21]:
v1

array([1, 2, 3, 4, 5])

In [22]:
v1 + 1

array([2, 3, 4, 5, 6])

In [23]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [24]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])