# Multiple linear regression

## Import the relevant libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [4]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [5]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Create the multiple linear regression

### Declare the dependent and independent variables

In [6]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Regression itself

In [7]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

0.29603261264909486

### Calculating the R-squared

In [10]:
reg.score(x, y)

0.40668119528142843

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1 - R^2)*\frac{n-1}{n-p-1}$

In [11]:
x.shape

(84, 2)

In [12]:
r2 = reg.score(x, y)

n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p -1)
adjusted_r2

0.39203134825134023

### Feature selection

In [13]:
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [15]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [16]:
p_values.round(3)

array([0.   , 0.676])

### Creating a summary table

In [17]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [ ]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)
reg_summary